<<<<<<< HEAD
spring.datasource.url=jdbc:mysql://localhost:3306/foyer_db?createDatabaseIfNotExist=true
=======
spring.datasource.url=jdbc:mysql://localhost:3307/foyer_db?createDatabaseIfNotExist=true
>>>>>>> 11083699458e0e2b2cb002b4bc3f3fa633dbd8d9
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true